package com.gigmed.riskengine.dao;

// Generated Feb 3, 2015 3:08:05 PM by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Inputdataset generated by hbm2java
 */
@Entity
@Table(name = "inputdataset", catalog = "gigmed")
public class Inputdataset implements java.io.Serializable {

	private Integer id;
	private String datasetId;
	private String externalId;
	private String diagnosis1;
	private String diagnosis2;
	private String diagnosis3;
	private String drugName;

	public Inputdataset() {
	}

	public Inputdataset(String datasetId, String externalId, String diagnosis1,
			String diagnosis2, String diagnosis3, String drugName) {
		this.datasetId = datasetId;
		this.externalId = externalId;
		this.diagnosis1 = diagnosis1;
		this.diagnosis2 = diagnosis2;
		this.diagnosis3 = diagnosis3;
		this.drugName = drugName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "datasetId", length = 65535)
	public String getDatasetId() {
		return this.datasetId;
	}

	public void setDatasetId(String datasetId) {
		this.datasetId = datasetId;
	}

	@Column(name = "externalId", length = 65535)
	public String getExternalId() {
		return this.externalId;
	}

	public void setExternalId(String externalId) {
		this.externalId = externalId;
	}

	@Column(name = "diagnosis1", length = 65535)
	public String getDiagnosis1() {
		return this.diagnosis1;
	}

	public void setDiagnosis1(String diagnosis1) {
		this.diagnosis1 = diagnosis1;
	}

	@Column(name = "diagnosis2", length = 65535)
	public String getDiagnosis2() {
		return this.diagnosis2;
	}

	public void setDiagnosis2(String diagnosis2) {
		this.diagnosis2 = diagnosis2;
	}

	@Column(name = "diagnosis3", length = 65535)
	public String getDiagnosis3() {
		return this.diagnosis3;
	}

	public void setDiagnosis3(String diagnosis3) {
		this.diagnosis3 = diagnosis3;
	}

	@Column(name = "drugName", length = 65535)
	public String getDrugName() {
		return this.drugName;
	}

	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}

}
